"""
Waze Voice Prompts Definition and German Script Presets.
Contains all 43 valid Waze audio filenames mapped to their categories,
official descriptions, and ready-to-use German text templates.
"""

from typing import Dict, List, Any

# Alle 43 exakten Waze-Dateinamen
VALID_WAZE_FILENAMES = [
    "200.mp3",
    "200meters.mp3",
    "400.mp3",
    "400meters.mp3",
    "800.mp3",
    "800meters.mp3",
    "1000meters.mp3",
    "1500.mp3",
    "1500meters.mp3",
    "AndThen.mp3",
    "ApproachAccident.mp3",
    "ApproachHazard.mp3",
    "ApproachRedLightCam.mp3",
    "ApproachSpeedCam.mp3",
    "ApproachTraffic.mp3",
    "Arrive.mp3",
    "ExitLeft.mp3",
    "ExitRight.mp3",
    "Fifth.mp3",
    "First.mp3",
    "Fourth.mp3",
    "KeepLeft.mp3",
    "KeepRight.mp3",
    "Police.mp3",
    "Roundabout.mp3",
    "Second.mp3",
    "Seventh.mp3",
    "Sixth.mp3",
    "StartDrive1.mp3",
    "StartDrive2.mp3",
    "StartDrive3.mp3",
    "StartDrive4.mp3",
    "StartDrive5.mp3",
    "StartDrive6.mp3",
    "StartDrive7.mp3",
    "StartDrive8.mp3",
    "StartDrive9.mp3",
    "Straight.mp3",
    "Third.mp3",
    "TickerPoints.mp3",
    "TurnLeft.mp3",
    "TurnRight.mp3",
    "uturn.mp3",
]

PROMPT_METADATA: Dict[str, Dict[str, Any]] = {
    # --- Start der Fahrt ---
    "StartDrive1.mp3": {
        "title": "Start der Fahrt (1)",
        "category": "start",
        "description": "Erste Start-Ansage zu Beginn der Route",
        "standard": "Alles bereit. Gute Fahrt!",
        "funny": "Schnall dich an, ich will nicht sterben!",
        "youtuber_gaming": "Jo Freunde, schnallt euch an, wir ballern los!",
        "choleriker": "Fahr endlich los, wir haben keine Zeit!",
    },
    "StartDrive2.mp3": {
        "title": "Start der Fahrt (2)",
        "category": "start",
        "description": "Alternative Start-Ansage (2)",
        "standard": "Route berechnet. Bitte vorsichtig fahren!",
        "funny": "Ich hoffe, du hast deinen Führerschein nicht im Lotto gewonnen.",
        "youtuber_gaming": "Chat, die Route steht. Abfahrt!",
        "choleriker": "Gott sei Dank geht's endlich weiter...",
    },
    "StartDrive3.mp3": {
        "title": "Start der Fahrt (3)",
        "category": "start",
        "description": "Alternative Start-Ansage (3)",
        "standard": "Navigation gestartet. Los geht's!",
        "funny": "Handy weg und Augen auf die Straße!",
        "youtuber_gaming": "Runde startet, keine Missplays heute!",
        "choleriker": "Fahr vorsichtig, die Straßen sind voller Idioten!",
    },
    "StartDrive4.mp3": {
        "title": "Start der Fahrt (4)",
        "category": "start",
        "description": "Alternative Start-Ansage (4)",
        "standard": "Fahrt beginnt. Sichere Weiterfahrt!",
        "funny": "Musik an, Hirn aus? Nein, bitte Hirn anlassen!",
        "youtuber_gaming": "Ready check bestanden! Let's go!",
        "choleriker": "Und wehe wir stehen gleich wieder im Stau!",
    },
    "StartDrive5.mp3": {
        "title": "Start der Fahrt (5)",
        "category": "start",
        "description": "Alternative Start-Ansage (5)",
        "standard": "Alles klar, wir können starten!",
        "funny": "Wenn wir geblitzt werden, warst du am Steuer!",
        "youtuber_gaming": "Zieh durch! Safe Driving activated.",
        "choleriker": "Tritt aufs Gas, die Oma vor uns schläft schon wieder!",
    },
    "StartDrive6.mp3": {
        "title": "Start der Fahrt (6)",
        "category": "start",
        "description": "Alternative Start-Ansage (6)",
        "standard": "Bereit zum Abfahren.",
        "funny": "Waze ist scharfgeschaltet. Verfahr dich bloß nicht!",
        "youtuber_gaming": "Mashallah, die Straßen sind frei. Abfahrt!",
        "choleriker": "Ich hoffe du weißt, wo das Gaspedal ist!",
    },
    "StartDrive7.mp3": {
        "title": "Start der Fahrt (7)",
        "category": "start",
        "description": "Alternative Start-Ansage (7)",
        "standard": "Ziel gesetzt, Fahrt beginnt.",
        "funny": "Ich bin deine Navigations-Stimme, nicht deine Mami. Pass auf!",
        "youtuber_gaming": "Next Level Navigation geladen!",
        "choleriker": "Los jetzt, grün wird's nicht mehr!",
    },
    "StartDrive8.mp3": {
        "title": "Start der Fahrt (8)",
        "category": "start",
        "description": "Alternative Start-Ansage (8)",
        "standard": "Gute Fahrt und pass auf dich auf!",
        "funny": "Bitte keine waghalsigen Drift-Versuche heute.",
        "youtuber_gaming": "Full Focus Modus an!",
        "choleriker": "Hände ans Lenkrad und Augen auf!",
    },
    "StartDrive9.mp3": {
        "title": "Start der Fahrt (9)",
        "category": "start",
        "description": "Alternative Start-Ansage (9)",
        "standard": "Bereit zur Abfahrt. Angenehme Reise!",
        "funny": "Navi läuft. Wenn wir uns verfahren, war die KI schuld.",
        "youtuber_gaming": "GG, wir starten den Run!",
        "choleriker": "Mach hinne, die Uhr tickt!",
    },

    # --- Richtungen & Manöver ---
    "TurnLeft.mp3": {
        "title": "Links abbiegen",
        "category": "directions",
        "description": "Befehl zum Linksabbiegen",
        "standard": "Biege links ab.",
        "funny": "Bieg links ab, sonst landen wir im Graben!",
        "youtuber_gaming": "Links abbiegen, aber zackig Digger!",
        "choleriker": "Links! Mensch, warum guckst du nach rechts?!",
    },
    "TurnRight.mp3": {
        "title": "Rechts abbiegen",
        "category": "directions",
        "description": "Befehl zum Rechtsabbiegen",
        "standard": "Biege rechts ab.",
        "funny": "Rechts abbiegen! Und Blinker setzen nicht vergessen.",
        "youtuber_gaming": "Rechts rüberziehen, let's go!",
        "choleriker": "Rechts rum! Da wo der Daumen links ist!",
    },
    "KeepLeft.mp3": {
        "title": "Links halten",
        "category": "directions",
        "description": "Befehl links zu bleiben",
        "standard": "Links halten.",
        "funny": "Halt dich links, nicht schlafen!",
        "youtuber_gaming": "Links bleiben, die Spur ist frei!",
        "choleriker": "Bleib gefälligst auf der linken Spur!",
    },
    "KeepRight.mp3": {
        "title": "Rechts halten",
        "category": "directions",
        "description": "Befehl rechts zu bleiben",
        "standard": "Rechts halten.",
        "funny": "Rechts halten, die linke Spur ist für die Schnellen!",
        "youtuber_gaming": "Rechts einsortieren!",
        "choleriker": "Rechts rüber, blockier hier nicht alles!",
    },
    "Straight.mp3": {
        "title": "Geradeaus weiterfahren",
        "category": "directions",
        "description": "Geradeaus fortsetzen",
        "standard": "Geradeaus weiterfahren.",
        "funny": "Einfach geradeaus. Das kriegst du doch hin, oder?",
        "youtuber_gaming": "Geradeaus durchballern!",
        "choleriker": "Immer geradeaus, mach keine Experimente!",
    },
    "uturn.mp3": {
        "title": "Wenden (U-Turn)",
        "category": "directions",
        "description": "Befehl zum Wenden",
        "standard": "Bitte wenden.",
        "funny": "Umdrehen! Du bist komplett falsch gefahren!",
        "youtuber_gaming": "Lost! Sofort umdrehen!",
        "choleriker": "Wenden! Hast du mir überhaupt zugehört?!",
    },
    "AndThen.mp3": {
        "title": "Und dann...",
        "category": "directions",
        "description": "Überleitung für doppelte Manöver",
        "standard": "Und danach...",
        "funny": "Und direkt im Anschluss...",
        "youtuber_gaming": "Und dann direkt Combo...",
        "choleriker": "Und danach sofort...",
    },
    "Arrive.mp3": {
        "title": "Ziel erreicht",
        "category": "directions",
        "description": "Ende der Fahrt am Zielort",
        "standard": "Du hast dein Ziel erreicht.",
        "funny": "Wir sind da! Endlich raus aus dieser Karre!",
        "youtuber_gaming": "Ziel erreicht, ez win! GG Chat!",
        "choleriker": "Endlich angekommen! Wurde auch höchste Zeit!",
    },

    # --- Kreisverkehr & Ausfahrten ---
    "Roundabout.mp3": {
        "title": "Im Kreisverkehr...",
        "category": "roundabout",
        "description": "Ansage vor Kreisverkehr-Einfahrt",
        "standard": "Im Kreisverkehr...",
        "funny": "Kreisel voraus! Nicht dreimal im Kreis fahren!",
        "youtuber_gaming": "Kreisverkehr gespottet!",
        "choleriker": "Kreisverkehr! Schau nach links, du Nase!",
    },
    "First.mp3": {
        "title": "Erste Ausfahrt",
        "category": "roundabout",
        "description": "1. Ausfahrt nehmen",
        "standard": "...die erste Ausfahrt nehmen.",
        "funny": "...gleich die erste Ausfahrt wieder raus!",
        "youtuber_gaming": "...erste Ausfahrt cutten!",
        "choleriker": "...erste Ausfahrt, mach zackig!",
    },
    "Second.mp3": {
        "title": "Zweite Ausfahrt",
        "category": "roundabout",
        "description": "2. Ausfahrt nehmen",
        "standard": "...die zweite Ausfahrt nehmen.",
        "funny": "...die zweite Ausfahrt raus.",
        "youtuber_gaming": "...zweite Ausfahrt nehmen!",
        "choleriker": "...die zweite Ausfahrt, zähl doch mit!",
    },
    "Third.mp3": {
        "title": "Dritte Ausfahrt",
        "category": "roundabout",
        "description": "3. Ausfahrt nehmen",
        "standard": "...die dritte Ausfahrt nehmen.",
        "funny": "...dritte Ausfahrt nehmen, nicht verpassen!",
        "youtuber_gaming": "...dritte Ausfahrt raus da!",
        "choleriker": "...dritte Ausfahrt, jetzt pass doch auf!",
    },
    "Fourth.mp3": {
        "title": "Vierte Ausfahrt",
        "category": "roundabout",
        "description": "4. Ausfahrt nehmen",
        "standard": "...die vierte Ausfahrt nehmen.",
        "funny": "...die vierte Ausfahrt! Einmal fast rum!",
        "youtuber_gaming": "...vierte Ausfahrt, fast 360!",
        "choleriker": "...vierte Ausfahrt! Fast wieder da, wo wir herkamen!",
    },
    "Fifth.mp3": {
        "title": "Fünfte Ausfahrt",
        "category": "roundabout",
        "description": "5. Ausfahrt nehmen",
        "standard": "...die fünfte Ausfahrt nehmen.",
        "funny": "...fünfte Ausfahrt nehmen.",
        "youtuber_gaming": "...fünfte Ausfahrt, weiter rum!",
        "choleriker": "...fünfte Ausfahrt raus!",
    },
    "Sixth.mp3": {
        "title": "Sechste Ausfahrt",
        "category": "roundabout",
        "description": "6. Ausfahrt nehmen",
        "standard": "...die sechste Ausfahrt nehmen.",
        "funny": "...sechste Ausfahrt nehmen. Schwindelig?",
        "youtuber_gaming": "...sechste Ausfahrt!",
        "choleriker": "...sechste Ausfahrt, was für ein Riesenkreisel!",
    },
    "Seventh.mp3": {
        "title": "Siebte Ausfahrt",
        "category": "roundabout",
        "description": "7. Ausfahrt nehmen",
        "standard": "...die siebte Ausfahrt nehmen.",
        "funny": "...siebte Ausfahrt! Wir drehen uns im Kreis!",
        "youtuber_gaming": "...siebte Ausfahrt!",
        "choleriker": "...siebte Ausfahrt, ich fass es nicht!",
    },
    "ExitLeft.mp3": {
        "title": "Ausfahrt links",
        "category": "roundabout",
        "description": "Ausfahrt auf der linken Seite nehmen",
        "standard": "Die Ausfahrt links nehmen.",
        "funny": "Ausfahrt links! Blinker raus und rüber!",
        "youtuber_gaming": "Links raus auf die Rampe!",
        "choleriker": "Links raus, verpass das bloß nicht!",
    },
    "ExitRight.mp3": {
        "title": "Ausfahrt rechts",
        "category": "roundabout",
        "description": "Ausfahrt auf der rechten Seite nehmen",
        "standard": "Die Ausfahrt rechts nehmen.",
        "funny": "Hier rechts abfahren!",
        "youtuber_gaming": "Rechts abfahren, let's go!",
        "choleriker": "Rechts raus! Jetzt zieh rüber!",
    },

    # --- Entfernungen ---
    "200meters.mp3": {
        "title": "In 200 Metern",
        "category": "distances",
        "description": "Kurzdistanz metrisch",
        "standard": "In 200 Metern...",
        "funny": "In zweihundert Metern, mach dich bereit!",
        "youtuber_gaming": "In zweihundert Metern...",
        "choleriker": "In zweihundert Metern!",
    },
    "400meters.mp3": {
        "title": "In 400 Metern",
        "category": "distances",
        "description": "Mitteldistanz metrisch",
        "standard": "In 400 Metern...",
        "funny": "In vierhundert Metern...",
        "youtuber_gaming": "In vierhundert Metern...",
        "choleriker": "In vierhundert Metern!",
    },
    "800meters.mp3": {
        "title": "In 800 Metern",
        "category": "distances",
        "description": "Langdistanz metrisch",
        "standard": "In 800 Metern...",
        "funny": "In achthundert Metern...",
        "youtuber_gaming": "In achthundert Metern...",
        "choleriker": "In achthundert Metern!",
    },
    "1000meters.mp3": {
        "title": "In 1 Kilometer",
        "category": "distances",
        "description": "1 km Ankündigung",
        "standard": "In einem Kilometer...",
        "funny": "In einem Kilometer kommt Action...",
        "youtuber_gaming": "In einem Kilometer...",
        "choleriker": "In einem Kilometer!",
    },
    "1500meters.mp3": {
        "title": "In 1,5 Kilometern",
        "category": "distances",
        "description": "1.5 km Ankündigung",
        "standard": "In 1,5 Kilometern...",
        "funny": "In eineinhalb Kilometern...",
        "youtuber_gaming": "In eineinhalb Kilometern...",
        "choleriker": "In eineinhalb Kilometern!",
    },
    "200.mp3": {
        "title": "In 200 Fuß / 0.1 Meilen",
        "category": "distances",
        "description": "Kurze Meilendistanz (Fallback)",
        "standard": "Gleich...",
        "funny": "Jetzt gleich...",
        "youtuber_gaming": "Gleich hier...",
        "choleriker": "Gleich!",
    },
    "400.mp3": {
        "title": "In einer viertel Meile",
        "category": "distances",
        "description": "Viertel-Meilendistanz",
        "standard": "In 400 Metern...",
        "funny": "In Kürze...",
        "youtuber_gaming": "In einer viertel Meile...",
        "choleriker": "Schon bald!",
    },
    "800.mp3": {
        "title": "In einer halben Meile",
        "category": "distances",
        "description": "Halbe Meilendistanz",
        "standard": "In 800 Metern...",
        "funny": "In knapp einem halben Kilometer...",
        "youtuber_gaming": "In einer halben Meile...",
        "choleriker": "Demnächst!",
    },
    "1500.mp3": {
        "title": "In einer Meile",
        "category": "distances",
        "description": "Eine Meilendistanz",
        "standard": "In 1,5 Kilometern...",
        "funny": "In etwa einer Meile...",
        "youtuber_gaming": "In einer Meile...",
        "choleriker": "Aufpassen, gleich kommt's!",
    },

    # --- Warnungen & Verkehr ---
    "Police.mp3": {
        "title": "Polizei voraus",
        "category": "alerts",
        "description": "Warnung vor Polizeikontrolle",
        "standard": "Polizei voraus gemeldet.",
        "funny": "Achtung, die Rennleitung steht da vorne! Schön brav bleiben!",
        "youtuber_gaming": "Achtung Digger, die Cops campen da vorne! Kein Stress!",
        "choleriker": "Cops voraus! Bloß nicht auffällig verhalten!",
    },
    "ApproachSpeedCam.mp3": {
        "title": "Fester Blitzer",
        "category": "alerts",
        "description": "Warnung vor Geschwindigkeitsblitzer",
        "standard": "Blitzer voraus.",
        "funny": "Blitzer! Geh vom Gas, dein Kontostand weint sonst!",
        "youtuber_gaming": "Blitzer voraus! Fuß vom Gas, nicht geiern!",
        "choleriker": "Blitzer! Tritt auf die Bremse, bist du blind?!",
    },
    "ApproachRedLightCam.mp3": {
        "title": "Ampelblitzer",
        "category": "alerts",
        "description": "Warnung vor Rotlichtkamera",
        "standard": "Ampelblitzer voraus.",
        "funny": "Ampelblitzer! Bei Gelb wird gebremst, Schlauberger!",
        "youtuber_gaming": "Ampelblitzer! Nicht riskieren!",
        "choleriker": "Ampelblitzer! Wehe du rutschst noch über Rot!",
    },
    "ApproachHazard.mp3": {
        "title": "Gefahr auf der Fahrbahn",
        "category": "alerts",
        "description": "Warnung vor Gefahrenstelle / Hindernis",
        "standard": "Gefahr auf der Fahrbahn gemeldet.",
        "funny": "Achtung, Hindernis auf der Straße! Augen auf!",
        "youtuber_gaming": "Hazard auf der Lane! Vorsichtig ausweichen!",
        "choleriker": "Schon wieder Zeug auf der Straße! Wer räumt das weg?!",
    },
    "ApproachTraffic.mp3": {
        "title": "Stau voraus",
        "category": "alerts",
        "description": "Warnung vor dichtem Verkehr oder Stau",
        "standard": "Stau voraus.",
        "funny": "Stau voraus... Zeit für gute Musik und schlechte Laune.",
        "youtuber_gaming": "Stau voraus... Komplett lost, wer steht hier schon wieder?!",
        "choleriker": "Stau! Ich raste aus! Wer hat diesen Mist geplant?!",
    },
    "ApproachAccident.mp3": {
        "title": "Unfall voraus",
        "category": "alerts",
        "description": "Warnung vor gemeldetem Unfall",
        "standard": "Unfall voraus gemeldet.",
        "funny": "Unfall voraus! Schau nach vorn und gaff nicht!",
        "youtuber_gaming": "Unfall gespottet, fahr vorsichtig vorbei!",
        "choleriker": "Unfall voraus! Da hat wieder einer gepennt!",
    },
    "TickerPoints.mp3": {
        "title": "Route neu berechnet",
        "category": "alerts",
        "description": "Neuberechnung bei Abweichung",
        "standard": "Route wird neu berechnet.",
        "funny": "Toll, verfahren. Ich rechne neu...",
        "youtuber_gaming": "Verklickt! Route wird neu kalkuliert.",
        "choleriker": "Warum fährst du falsch?! Ich muss schon wieder neu rechnen!",
    },
}

CATEGORIES = [
    {"id": "start", "name": "Start der Fahrt", "icon": "🚀"},
    {"id": "directions", "name": "Richtungen & Manöver", "icon": "🧭"},
    {"id": "roundabout", "name": "Kreisverkehr & Ausfahrten", "icon": "🔄"},
    {"id": "distances", "name": "Entfernungsangaben", "icon": "📏"},
    {"id": "alerts", "name": "Warnungen & Verkehrsmeldungen", "icon": "⚠️"},
]

PRESETS = {
    "standard": {
        "name": "Standard (Seriös & Klar)",
        "description": "Klare, präzise und professionelle Navigationsansagen auf Deutsch.",
    },
    "funny": {
        "name": "Lustig & Humorvoll",
        "description": "Frech, amüsant und mit humorvollen Sprüchen für mehr Spaß im Auto.",
    },
    "youtuber_gaming": {
        "name": "Streamer & Gaming Slang",
        "description": "Moderner YouTube/Twitch-Vibe mit Begriffen wie Digger, Lost, Mashallah und GG.",
    },
    "choleriker": {
        "name": "Cholerischer Beifahrer",
        "description": "Der dauergenervte Beifahrer, der sich über Stau, Blitzer und falsches Abbiegen aufregt.",
    },
}
